version: "3.9"

services:
  ryu:
    image: python:3.9-slim
    container_name: ryu-controller
    working_dir: /app
    volumes:
      - ./controller:/app/controller
      - ./requirements.txt:/app/requirements.txt
    command: >
      sh -c "pip install 'setuptools<65' --no-cache-dir &&
      pip install --no-cache-dir -r /app/requirements.txt &&
      ryu-manager /app/controller/acl_controller.py --ofp-tcp-listen-port 6653"

    ports:
      - "6653:6653"
      - "8080:8080"
    networks:
      - sdn_network

  mininet:
    image: iwaseyusuke/mininet
    container_name: mininet-topo
    privileged: true
    depends_on:
      - ryu
    working_dir: /app
    volumes:
      - ./topology:/app/topology
      - ./tests:/app/tests
    command: >
      python3 /app/tests/stimulate_user.py &&
      tail -f /dev/null"
    networks:
      - sdn_network
    stdin_open: true
    tty: true

networks:
  sdn_network:
    driver: bridge
